### ISSUE TITLE
Who should have write access to this repo

### ISSUE THREAD

**Issue by hwine** [mozilla-services/python-autograph-utils#12]
Currently, no one does.

Please suggest an existing team, or create one & I can assign write access.

@leplatrem @g-k

**Comment by leplatrem** [comment]
I would suggest Product Delivery https://github.com/orgs/mozilla-services/teams/product-delivery but that would exclude Greg.

Maybe it's better to create one for `autograph` with at least @g-k @mythmon and I for now

**Comment by hwine** [comment]
done - new team [autograph-writers](https://github.com/orgs/mozilla-services/teams/autograph-writers) with @g-k as maintainer.
